services:
  db:
    container_name: letterboxd-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: letterboxd_db
      POSTGRES_USER: letterboxd
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    container_name: letterboxd
    env_file:
      - .env
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=letterboxd_db
      - POSTGRES_USER=letterboxd
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  db_data:
